# -*- mode: ruby -*-
# vi: set ft=ruby :
# Sample Vagranfile to setup Learning Environment
# for Ansible Playbook Essentials

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = false

    config.vm.define "control" do |control|
        control.vm.network :private_network, ip: "192.168.61.10"
    end

    config.vm.define "db" do |db|
        db.vm.network :private_network, ip: "192.168.61.11"
    end

    config.vm.define "dbel" do |dbel|
        dbel.vm.network :private_network, ip: "192.168.61.14"
        dbel.vm.box = "puphpet/centos65-x64"
    end

    config.vm.define "www" do |www|
        www.vm.network :private_network, ip: "192.168.61.12"
    end

    config.vm.define "lb" do |lb|
        lb.vm.network :private_network, ip: "192.168.61.13"
    end
end